"""Datos iniciales del catálogo de obligaciones (referencia España)."""
import json

OBLIGACIONES = [
    {
        'codigo': 'RGPD',
        'nombre': 'Protección de Datos (RGPD/LOPDGDD)',
        'categoria': 'proteccion_datos',
        'descripcion': 'Cumplimiento del Reglamento General de Protección de Datos',
        'normativa': 'Reglamento UE 2016/679 y Ley Orgánica 3/2018',
        'condiciones_json': json.dumps({
            'OR': [
                {'tiene_empleados': True},
                {'trata_datos_personales': True},
                {'tiene_web': True},
                {'tiene_rrss': True},
            ]
        }),
        'items_json': json.dumps([
            'Registro de Actividades de Tratamiento',
            'Política de Privacidad',
            'Contratos con Encargados de Tratamiento',
            'Análisis de Riesgos',
            'Procedimiento de Brechas de Seguridad',
            'Información a Interesados (cláusulas)',
        ]),
        'obligatoria': True,
        'recomendada': False,
        'plazo': 'INMEDIATO',
        'sancion_min': 0,
        'sancion_max': 20000000,
        'sancion_descripcion': 'Hasta 20.000.000€ o 4% de la facturación anual global',
        'orden_prioridad': 1,
    },
    {
        'codigo': 'PRL',
        'nombre': 'Prevención de Riesgos Laborales',
        'categoria': 'laboral',
        'descripcion': 'Servicio de Prevención de Riesgos Laborales',
        'normativa': 'Ley 31/1995 de Prevención de Riesgos Laborales',
        'condiciones_json': json.dumps({'num_empleados_actual': {'>=': 1}}),
        'items_json': json.dumps([
            'Evaluación de Riesgos de cada puesto',
            'Planificación de la Actividad Preventiva',
            'Vigilancia de la Salud (reconocimientos médicos)',
            'Formación en PRL para empleados',
            'Información sobre riesgos y medidas preventivas',
            'Equipos de Protección Individual (si procede)',
        ]),
        'obligatoria': True,
        'recomendada': False,
        'plazo': 'Antes de la contratación del primer empleado',
        'sancion_min': 8195,
        'sancion_max': 983736,
        'sancion_descripcion': 'De 8.195€ a 983.736€ según gravedad',
        'orden_prioridad': 2,
    },
    {
        'codigo': 'REG_HORARIO',
        'nombre': 'Registro Horario Obligatorio',
        'categoria': 'laboral',
        'descripcion': 'Sistema de registro diario de jornada',
        'normativa': 'Real Decreto-ley 8/2019',
        'condiciones_json': json.dumps({'num_empleados_actual': {'>=': 1}}),
        'items_json': json.dumps([
            'Sistema de fichaje diario (entrada y salida)',
            'Conservación durante 4 años',
            'Disponible para Inspección de Trabajo',
            'Acceso de representantes de trabajadores',
        ]),
        'obligatoria': True,
        'recomendada': False,
        'plazo': 'INMEDIATO',
        'sancion_min': 751,
        'sancion_max': 7500,
        'sancion_descripcion': 'De 751€ a 7.500€',
        'orden_prioridad': 3,
    },
    {
        'codigo': 'REG_SALARIAL',
        'nombre': 'Registro Salarial (Igualdad Retributiva)',
        'categoria': 'laboral',
        'descripcion': 'Registro retributivo de la plantilla',
        'normativa': 'Real Decreto 902/2020',
        'condiciones_json': json.dumps({'num_empleados_actual': {'>=': 1}}),
        'items_json': json.dumps([
            'Registro retributivo desagregado por sexo',
            'Valores medios de salarios',
            'Justificación de diferencias superiores al 25%',
            'Actualización anual',
        ]),
        'obligatoria': True,
        'recomendada': False,
        'plazo': 'Vigente desde abril 2021',
        'sancion_min': 751,
        'sancion_max': 7500,
        'sancion_descripcion': 'De 751€ a 7.500€',
        'orden_prioridad': 4,
    },
    {
        'codigo': 'PLAN_IGUALDAD',
        'nombre': 'Plan de Igualdad',
        'categoria': 'laboral',
        'descripcion': 'Plan de Igualdad negociado y registrado',
        'normativa': 'Ley Orgánica 3/2007 y RD 901/2020',
        'condiciones_json': json.dumps({'num_empleados_actual': {'>=': 50}}),
        'items_json': json.dumps([
            'Diagnóstico de situación',
            'Negociación con representantes legales de trabajadores',
            'Redacción e implantación del Plan',
            'Registro en REGCON',
            'Seguimiento y evaluación anual',
        ]),
        'obligatoria': True,
        'recomendada': False,
        'plazo': 'Según fecha de inscripción en REGCON',
        'sancion_min': 751,
        'sancion_max': 187515,
        'sancion_descripcion': 'De 751€ a 187.515€',
        'orden_prioridad': 5,
    },
    {
        'codigo': 'CANAL_DENUNCIAS',
        'nombre': 'Canal de Denuncias (Whistleblowing)',
        'categoria': 'compliance',
        'descripcion': 'Sistema interno de información sobre infracciones',
        'normativa': 'Ley 2/2023 de 20 de febrero',
        'condiciones_json': json.dumps({'num_empleados_actual': {'>=': 50}}),
        'items_json': json.dumps([
            'Sistema interno de información seguro',
            'Garantía de confidencialidad del denunciante',
            'Procedimiento de gestión de denuncias',
            'Prohibición de represalias',
            'Información y formación a empleados',
        ]),
        'obligatoria': True,
        'recomendada': False,
        'plazo': 'Vigente desde 1 de diciembre de 2023',
        'sancion_min': 0,
        'sancion_max': 1000000,
        'sancion_descripcion': 'Hasta 1.000.000€ según infracción',
        'orden_prioridad': 6,
    },
    {
        'codigo': 'LIC_APERTURA',
        'nombre': 'Licencia de Apertura',
        'categoria': 'local',
        'descripcion': 'Licencia municipal de actividad y apertura',
        'normativa': 'Ordenanza municipal correspondiente',
        'condiciones_json': json.dumps({'tiene_local': True}),
        'items_json': json.dumps([
            'Licencia de Apertura vigente',
            'Certificado de Instalación Eléctrica',
            'Certificado de Instalación de Gas (si procede)',
            'Inspección de Climatización (si potencia >70kW)',
            'Certificado de Actividad Inocua o Licencia de Actividad',
        ]),
        'obligatoria': True,
        'recomendada': False,
        'plazo': 'Antes de iniciar la actividad',
        'sancion_min': 300,
        'sancion_max': 3000,
        'sancion_descripcion': 'De 300€ a 3.000€ + posible cierre cautelar',
        'orden_prioridad': 7,
    },
    {
        'codigo': 'SEG_RC',
        'nombre': 'Seguro de Responsabilidad Civil',
        'categoria': 'seguros',
        'descripcion': 'Póliza de Responsabilidad Civil General',
        'normativa': 'Según actividad y normativa sectorial',
        'condiciones_json': json.dumps({
            'OR': [
                {'tipo_sociedad': {'in': ['sl', 'sa', 'cooperativa']}},
                {'num_empleados_actual': {'>=': 1}},
                {'tiene_local': True},
            ]
        }),
        'items_json': json.dumps([
            'Póliza RC General vigente',
            'Cobertura mínima según actividad',
            'Inclusión de personal y bienes',
            'Renovación anual',
        ]),
        'obligatoria': False,
        'recomendada': True,
        'plazo': 'MUY RECOMENDADO',
        'sancion_min': 0,
        'sancion_max': 0,
        'sancion_descripcion': 'Riesgo patrimonial ante reclamaciones',
        'orden_prioridad': 8,
    },
    {
        'codigo': 'SEG_LOCAL',
        'nombre': 'Seguro Multirriesgo del Local',
        'categoria': 'seguros',
        'descripcion': 'Seguro de continente y contenido',
        'normativa': 'No obligatorio legalmente (salvo contrato de arrendamiento)',
        'condiciones_json': json.dumps({'tiene_local': True}),
        'items_json': json.dumps([
            'Póliza Multirriesgo vigente',
            'Cobertura de Continente (edificio)',
            'Cobertura de Contenido (mobiliario, equipos)',
            'Coberturas adicionales: robo, cristales, responsabilidad civil',
        ]),
        'obligatoria': False,
        'recomendada': True,
        'plazo': 'MUY RECOMENDADO',
        'sancion_min': 0,
        'sancion_max': 0,
        'sancion_descripcion': 'Riesgo patrimonial en siniestro',
        'orden_prioridad': 9,
    },
    {
        'codigo': 'SEG_CONVENIO',
        'nombre': 'Seguro de Convenio (Trabajadores)',
        'categoria': 'seguros',
        'descripcion': 'Seguro colectivo establecido en Convenio Colectivo',
        'normativa': 'Convenio Colectivo aplicable',
        'condiciones_json': json.dumps({
            'AND': [
                {'num_empleados_actual': {'>=': 1}},
                {'convenio_aplicable': {'!=': None}},
            ]
        }),
        'items_json': json.dumps([
            'Póliza colectiva según Convenio',
            'Coberturas establecidas en Convenio (vida, invalidez, accidentes)',
            'Renovación según periodicidad del Convenio',
        ]),
        'obligatoria': True,
        'recomendada': False,
        'plazo': 'Según Convenio Colectivo',
        'sancion_min': 751,
        'sancion_max': 7500,
        'sancion_descripcion': 'Infracciones laborales por incumplimiento de convenio',
        'orden_prioridad': 10,
    },
    {
        'codigo': 'COMPLIANCE_PENAL',
        'nombre': 'Programa de Compliance Penal',
        'categoria': 'compliance',
        'descripcion': 'Modelo de prevención de delitos corporativos',
        'normativa': 'Ley Orgánica 1/2015 reforma del Código Penal',
        'condiciones_json': json.dumps({
            'OR': [
                {
                    'AND': [
                        {'tipo_sociedad': {'in': ['sl', 'sa']}},
                        {'num_empleados_actual': {'>=': 10}},
                    ]
                },
                {'facturacion_estimada': {'>': 2000000}},
            ]
        }),
        'items_json': json.dumps([
            'Identificación de riesgos penales (mapa de riesgos)',
            'Código Ético',
            'Procedimientos de prevención',
            'Canal de Denuncias',
            'Órgano de Compliance',
            'Formación periódica en compliance',
        ]),
        'obligatoria': False,
        'recomendada': True,
        'plazo': 'MUY RECOMENDABLE',
        'sancion_min': 0,
        'sancion_max': 0,
        'sancion_descripcion': 'Eximente o atenuante de responsabilidad penal de la persona jurídica',
        'orden_prioridad': 11,
    },
    {
        'codigo': 'BLANQUEO_CAPITALES',
        'nombre': 'Prevención de Blanqueo de Capitales',
        'categoria': 'compliance',
        'descripcion': 'Medidas de prevención del blanqueo y financiación del terrorismo',
        'normativa': 'Ley 10/2010',
        'condiciones_json': json.dumps({
            'OR': [
                {
                    'cnae_principal': {
                        'in': [
                            '4110', '4120', '6810', '6820', '6910', '6920',
                            '7740', '9104', '3212', '7711',
                        ]
                    }
                },
                {'opera_efectivo': {'in': ['regular', 'ocasional']}},
            ]
        }),
        'items_json': json.dumps([
            'Manual de Prevención de Blanqueo',
            'Diligencia debida sobre clientes',
            'Declaración de operaciones sospechosas',
            'Formación del personal',
            'Órgano de control interno',
            'Conservación de documentos (10 años)',
        ]),
        'obligatoria': True,
        'recomendada': False,
        'plazo': 'INMEDIATO para sujetos obligados',
        'sancion_min': 0,
        'sancion_max': 150000,
        'sancion_descripcion': 'Hasta 150.000€ o 5% de la facturación',
        'orden_prioridad': 12,
    },
    {
        'codigo': 'CERT_DIGITAL',
        'nombre': 'Certificado Digital de Empresa',
        'categoria': 'identificacion',
        'descripcion': 'Certificado electrónico para trámites telemáticos',
        'normativa': 'Ley 39/2015 del Procedimiento Administrativo Común',
        'condiciones_json': json.dumps({
            'tipo_sociedad': {'in': ['sl', 'sa', 'cooperativa', 'comunidad_bienes']}
        }),
        'items_json': json.dumps([
            'Certificado Digital de la entidad',
            'Certificado del representante legal',
            'Renovación antes del vencimiento (validez 2-4 años)',
        ]),
        'obligatoria': True,
        'recomendada': False,
        'plazo': 'INMEDIATO',
        'sancion_min': 0,
        'sancion_max': 0,
        'sancion_descripcion': 'Imposibilidad de trámites telemáticos con AAPP',
        'orden_prioridad': 13,
    },
    {
        'codigo': 'APPCC',
        'nombre': 'Plan APPCC + Registro Sanitario',
        'categoria': 'sanitario',
        'descripcion': 'Análisis de Peligros y Puntos de Control Crítico',
        'normativa': 'Reglamento CE 852/2004',
        'condiciones_json': json.dumps({'manipula_alimentos': True}),
        'items_json': json.dumps([
            'Plan APPCC específico de la actividad',
            'Registro Sanitario',
            'Formación de manipuladores de alimentos',
            'Plan de limpieza y desinfección (L+D)',
            'Control de proveedores',
            'Trazabilidad',
        ]),
        'obligatoria': True,
        'recomendada': False,
        'plazo': 'Antes de iniciar la actividad',
        'sancion_min': 300,
        'sancion_max': 600000,
        'sancion_descripcion': 'De 300€ a 600.000€ + cierre',
        'orden_prioridad': 14,
    },
]
